### ISSUE TITLE
need to add to readme about installing 'MMKV' via pod

### ISSUE THREAD

**Issue by thienpow** [FidMe/react-native-fast-storage#1]
**Add the required pods**
add the following to your Podfile either at the top level, or within the main project target:
`# pod for MMKV required by react-native-fast-storage`
`pod 'MMKV'`

**Comment by thienpow** [comment]
and for android, inside app/build.gradle

dependencies {
    implementation 'com.tencent:mmkv:1.0.10'

**Comment by Michaelvilleneuve** [comment]
Hi, adding that line for android should not be necessary as the lib is already included as a sub dependency by this project.
For iOS that would be doable, but it is not only a Readme change since I included the `.framework` right in the project

**Comment by thienpow** [comment]
<img width="328" alt="screenshot 2018-09-29 at 12 46 48 am" src="https://user-images.githubusercontent.com/9796623/46222397-b97de300-c382-11e8-923d-d4e19bcac373.png">

can't get the android working.  iOS is ok

**Comment by thienpow** [comment]
I am on Xcode 10, 
"react-native": "0.57.1",
node v10.10.0

**Comment by Michaelvilleneuve** [comment]
The lib does not seem to be correctly linked, can you check your linking? Or do it manually ? Thanks

**Comment by thienpow** [comment]
got it working.
I am using react-native-navigation
seems like react-native link or react-native link react-native-fast-storage doesn't add this line to the code: `new RNFastStoragePackage()`

`  protected List<ReactPackage> getPackages() {`
`      // Add additional packages you require here`
`      // No need to add RnnPackage and MainReactPackage`
`      return Arrays.<ReactPackage>asList(`
`         // eg. new VectorIconsPackage()`
`          new RNFastStoragePackage(), // <----- this line`
`      );`
`  }`

**Comment by Michaelvilleneuve** [comment]
Oh I see, sounds more like a problem with the way react native navigation modifies the default RN file structure

**Comment by jordanmkoncz** [comment]
I also found that my iOS app was not able to build/run after following the instructions in the readme. I created a separate issue about it here: https://github.com/FidMe/react-native-fast-storage/issues/2.

It's possible that an alternative way to resolve the issue is to manually install the `MMKV` pod, however I think with this approach you would be using whatever version of the `MMKV` library you've installed via CocoaPods rather than the version that is included in `react-native-fast-storage` (i.e. `../node_modules/react-native-fast-storage/ios/MMKV.framework`), which could create problems if the version you've installed via CocoaPods is different than the one expected by `react-native-fast-storage` and not compatible with it. So this is probably not the best approach, and it's probably safer to use the solution I found so that your app is using the version of MMKV that is provided by `react-native-fast-storage`.
